# Default values for dremio-module.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imageChart: 
  repository: ghcr.io/tomersolomon1/dremio-module-register
  tag: main
  pullPolicy: Always
  pullSecret: null

imageChartClean: 
  repository: ghcr.io/tomersolomon1/dremio-module-clean
  tag: main
  pullPolicy: Always
  pullSecret: null

restartPolicy: Never
imagePullSecrets: []

dremioCluster:
  host: ""
  port: ""
  enabled: false


serviceChart:
  type: ClusterIP
  port: 80

# Dremio Service
# The dremio-client service exposes the service for access outside of the Kubernetes cluster.
service:
  type: NodePort

  # These values, when defined and not empty, override the provided shared annotations and labels.
  # Uncomment only if you are trying to override the chart's shared values.
  #annotations: {}
  #labels: {}

  # If the loadBalancer supports sessionAffinity and you have more than one coordinator,
  # uncomment the below line to enable session affinity.
  #sessionAffinity: ClientIP

  # Enable the following flag if you wish to route traffic through a shared VPC
  # for the LoadBalancer's external IP.
  # The chart is setup for internal IP support for AKS, EKS, GKE.
  # For more information, see https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
  #internalLoadBalancer: true

  # If you have a static IP allocated for your load balancer, uncomment the following
  # line and set the IP to provide the static IP used for the load balancer.
  # Note: The service type must be set to LoadBalancer for this value to be used.
  #loadBalancerIP: 0.0.0.0

# To use custom storage class, uncomment below.
# Otherwise the default storage class configured for your K8s cluster is used.
#storageClass: managed-premium

# For private and protected docker image repository, you should store
# the credentials in a kubernetes secret and provide the secret name
# here.  For more information, see
# https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
# imagePullSecrets:
#  - secretname

resources: {}