apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dremio-module.fullname" . }}
{{- if .Values.imageChart.pullSecret }}
imagePullSecrets: 
  - name: {{ .Values.imageChart.pullSecret }}
{{- end }}